freq_step: 20
max_num_peaks: 7
max_num_workers: 14
chunk_size: 2000
debug: false
debug_range:
- 50
- 100
cache_dir: ./local_cache
output_dir: ./ml_data
parquet_file: ./data/Experiment_Table.parquet
processed_path: ./data/processed/
min_signal_amplitude: 0.01
max_signal_amplitude: 0.99
min_signal_length_seconds: 0.1
min_snr_db: 5.0
clipping_tolerance_percentage: 0.5
dc_offset_threshold: 0.1
save_formats:
- csv
- parquet
log_level: INFO
log_directory: ./logs
report_directory: ./reports
max_log_size_mb: 50.0
log_rotation_count: 3
audio_preprocessing:
  enable_trimming: true
  trim_start_seconds: 0.4
  trim_end_seconds: 0.1
  min_duration_for_trim: 0.6
  normalize_audio: true
  target_rms_level: 0.1
spectral_analysis:
  window_function: hann
  fft_overlap_percentage: 50
  min_peak_prominence: 0.5
  min_peak_distance_hz: 100
processing_options:
  skip_existing_analysis: true
  force_reprocess_all: false
  include_full_spectrogram: false
  cache_raw_audio: false
CONFIG_FILE: ./config/processing_config.yaml
